# Generated by Django 6.0.5 on 2026-06-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_chat_room_created_by_alter_media_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_room',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
